name: Unit Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker build
      run: docker-compose build
        
    - name: Setup Docker build
      run: |
        docker-compose run api rake db:create
        docker-compose run api rake db:migrate