name: Unit Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Build
      run: docker-compose build
        
    - name: Setup Docker Build and Test
      run: |
        docker-compose run api rake db:create
        docker-compose run api rake db:migrate

    - name: Docker Down
      run: docker container ls

    - name: Run Unit Test
      run: docker exec -it rails_dockerizing_db_1 bundle exec rails test